version: "3"
services:
  web:
    build: .
    env_file: .env_docker
    ports:
      - "3000:3000"
    links:
      - mongo
      - ai
  mongo:
    image: mongo
  ai:
    image: medo/aimock
    ports:
      - "5555:5555"